// Socket
    {"isenabledsock",   basIsEnabledSock,   0,  0},

    {"getfreesock",     basGetFreeSock,     0,  0},
    {"opensock",        basOpenSock,        1,  0},
    {"acceptsock",      basAcceptSock,      1,  0},
    {"isserverready",   basIsServerReady,   1,  0},
    {"connectsock",     basConnectSock,     2,  0},
  //{"connectionreadysock",basConnectionReadySock,1,  0},
    {"isclientready",   basIsClientReady,   1,  0},
    {"closesock",       basCloseSock,       1,  0},
  //{"peeksock",        basPeekSock,        2,  0},
    {"readsock",        basReadSock,        2,  0},
    {"readbytesock",    basReadByteSock,    1,  0},
    {"readlinesock",    basReadLineSock,    1,  0},
    {"writesock",       basWriteSock,       3,  0},
    {"writebytesock",   basWriteByteSock,   2,  0},
    {"writelinesock",   basWriteLineSock,   2,  0},
    {"getremoteip",     basGetRemoteIp,     1,  0},
    {"getremoteport",   basGetRemotePort,   1,  0},
    {"getlocalip",     	basGetLocalIp,      0,  0},
