
/***************** SDLengine *********************/
//    Screen
    {"setdefaults",     basSetDefaults,     4,  0},
    {"setdisplay",      basSetDisplay,      4,  0},
    {"setalphachannel", basSetAlphaChannel, 1,  0},
    {"setcaption",      basSetCaption,      1,  0},
    {"caption",      	basCaption,         0,  0},
    
    {"systemwidth",   basSystemWidth,     0,  0},
    {"systemheight",  basSystemHeight,     0,  0},
    {"displaymode",    basDisplayMode,     0,  0},
    {"displaywidth",    basDisplayWidth,    0,  0},
    {"displayheight",   basDisplayHeight,   0,  0},
    {"displaybpp",      basDisplayBpp,      0,  0},

    {"screen",          basScreen,	    0,  1},
    {"screenz",         basScreenZ,	    1,  1},
    {"lastscreen",      basLastScreen,	    0,  0},
    {"directscreen",    basDirectScreen,    0,  0},
    {"screenopen",      basScreenOpen,	    8,  0},
    {"screenclose",     basScreenClose,	    1,  0},
    {"screenclone",     basScreenClone,	    7,  0},

    {"screencopy",      basScreenCopy,	    8,  0},
    {"screenfade",      basScreenFade,	    1,  1},
    {"screenfadeout",   basScreenFade,	    1,  1},
    {"screenfadein",    basScreenFadein,    1,  2},
    {"screencrossfade", basScreenCrossFade, 1,  2},
    {"screenalpha",     basScreenAlpha,     2,  0},
    {"screenlock",      basScreenLock,      1,  0},
    {"screenunlock",    basScreenUnlock,    1,  0},

    {"screenrect",      basScreenRect,	    5,  0},
    {"screenviewport",  basScreenRect,	    5,  0},
    {"xscreenrect",     basXScreenRect,	    0,  0},
    {"screenviewportx", basXScreenRect,	    0,  0},
    {"yscreenrect",     basYScreenRect,	    0,  0},
    {"screenviewporty", basYScreenRect,	    0,  0},
    {"wscreenrect",     basWScreenRect,	    0,  0},
    {"screenviewportw", basWScreenRect,	    0,  0},
    {"hscreenrect",     basHScreenRect,	    0,  0},
    {"screenviewporth", basHScreenRect,	    0,  0},
    {"flagscreenrect",  basFlagScreenRect,  0,  0},
    {"screenviewportflag",basFlagScreenRect,  0,  0},

    {"screenwidth",     basScreenWidth,	    0,  0},
    {"screenheight",    basScreenHeight,    0,  0},

    {"offset",  	basOffset,	    2,  0},
    {"screenoffset",  	basOffset,	    2,  0},
    {"xoffset", 	basXOffset,   	    0,  0},
    {"screenoffsetx", 	basXOffset,   	    0,  0},
    {"yoffset", 	basYOffset,         0,  0},
    {"screenoffsety", 	basYOffset,         0,  0},

    {"cls",				basCls,     	    0,  0},
    {"screenswap",      basScreenSwap,      0,  0},
    {"setautoback",     basAutoBack,        0,  1},
    {"autoback",    	basAutoBack,        0,  1},
    {"dualplayfield",   basDualPlayfield,   0,  1},
    {"waitvbl",     	basWaitVbl,         0,  0},
    {"fps",         	basFps,             0,  1},

//    Graphics
    {"rgb",     	basRgb,      	    3,  0},
    {"enablepalette",  	basEnablePalette,   0,  1},
    {"color",     	basColor,      	    1,  1},
    {"palette",     	basPalette,         0,  255},
    {"colorcycling",    basColorCycling,    0,  4},
    {"ink",     	basInk,      	    0,  1},

    {"point",     	basPoint,      	    2,  0},
    {"getpixel",     	basPoint,      	    2,  0},
    {"dot",     	basDot,      	    2,  0},
    {"setpixel",     	basDot,      	    2,  0},
    {"putpixel",     	basDot,      	    2,  0},
    {"plot",     	basPlot,      	    3,  0},
    {"line",     	basLine,      	    4,  0},
    {"box",     	basBox,      	    4,  0},
    {"bar",     	basBar,      	    4,  0},
    {"rectangle",     	basRectangle, 	    4,  1},
    {"circle",     	basCircle,     	    3,  0},
    {"fillcircle",      basFillCircle, 	    3,  0},
    {"ellipse",         basEllipse,   	    4,  0},
    {"fillellipse",     basFillEllipse,	    4,  0},
    {"paint",		basPaint,	    2,  0},
    {"triangle",	basTriangle,	    6,  0},
    {"polyline",	basPolyLine,	    6,  254},
    {"polygon",		basPolyGon,	    6,  254},

//    File graphics input output
    {"loadimage",       basLoadImage,	    1,  1},
    {"loadzipimage",    basLoadZipImage,    2,  1},
    {"saveimage",       basSaveImage,	    2,  0},
    {"loadsound",       basLoadSound,	    1,  1},
    {"loadzipsound",    basLoadZipSound,    2,  1},
    {"savesound",       basSaveSound,	    2,  0},
    {"loadmusic",       basLoadMusic,	    1,  0},
    {"loadzipmusic",    basLoadZipMusic,    2,  0},

//    Image manipulation
    {"hotspot",      	basHotSpot,	    3,  0},
    {"setcolorkey",     basSetColorKey,	    1,  0},
    {"colorkey",        basSetColorKey,	    1,  0},
    {"imageexists",  	basImageExists,	    1,  0},
    {"imagewidth",   	basImageWidth,	    1,  0},
    {"imageheight",  	basImageHeight,	    1,  0},
    {"deleteimage",  	basDeleteImage,	    1,  0},
    {"copyimage",    	basCopyImage,	    2,  0},
    {"setalpha",     	basSetAlpha,	    2,  0},
    {"imagealpha",     	basSetAlpha,	    2,  0},
    {"zoomimage",     	basZoomImage,	    3,  0},
    {"rotateimage",    	basRotateImage,	    2,  0},
    {"rotozoomimage",  	basRotozoomImage,   3,  0},
    {"mirrorimage",  	basMirrorImage,     3,  0},

//    Blitting
    {"blt", 	      	basBlt,	            7,  0},
    {"pastebob",      	basPasteBob,        3,  0},
    {"pasteicon",     	basPasteIcon,       3,  0},
    {"grab",          	basGrab,            5,  0},

//    Sprite system
    {"spriteclip",    	basSpriteClip,      4,  0},
    {"sprite",        	basSprite,          4,  0},
    {"deletesprite",  	basDeleteSprite,    1,  0},
    {"xsprite",       	basXSprite,         1,  0},
    {"spritex",       	basXSprite,         1,  0},
    {"ysprite",       	basYSprite,         1,  0},
    {"spritey",       	basYSprite,         1,  0},
    {"spritewidth",   	basSpriteWidth,     1,  0},
    {"spriteheight",  	basSpriteHeight,    1,  0},
    {"frsprite",      	basFrSprite,        1,  0},
    {"spriteimage",    	basFrSprite,        1,  0},
    {"livesprite",    	basLiveSprite,      1,  0},
    {"spriteexist",    	basLiveSprite,      1,  0},
    {"spritehit",     	basSpriteHit,       1,  1},
    {"spritez",     	basSpriteZ,         1,  1},
    {"lastsprite",     	basLastSprite,      0,  0},
    {"autoupdatesprite",basAutoUpdateSprite,1,  0},
    {"updatesprite",  	basUpdateSprite,    0,  0},

//    Bob system
    {"setbob",        	basSetBob,          2,  0},
    {"bob",           	basBob    ,         4,  0},
    {"deletebob",     	basDeleteBob,       1,  0},
    {"xbob",          	basXBob,            1,  0},
    {"bobx",          	basXBob,            1,  0},
    {"ybob",          	basYBob,            1,  0},
    {"boby",          	basYBob,            1,  0},
    {"bobwidth",      	basBobWidth,        1,  0},
    {"bobheight",     	basBobHeight,       1,  0},
    {"frbob",         	basFrBob,           1,  0},
    {"bobimage",       	basFrBob,           1,  0},
    {"livebob",       	basLiveBob,         1,  0},
    {"bobexist",       	basLiveBob,         1,  0},
    {"bobhit",        	basBobHit,          1,  1},
    {"bobz",     	basBobZ,            1,  1},
    {"lastbob",     	basLastBob,         0,  0},
    {"autoupdatebob", 	basAutoUpdateBob,   1,  0},
    {"updatebob",     	basUpdateBob,       0,  0},

//    Text draw
    {"text",          	basText,            4,  1},
    {"setfont",       	basSetFont,         1,  0},
    {"getfont",       	basGetFont,         0,  0},
    {"textrender",    	basTextRender,      2,  2},

//    Print screen
    {"pen",    	      	basPen,             0,  1},
    {"paper",         	basPaper,           0,  1},
    {"fprints",       	basfPrints,         1,  0},
    {"prints",        	basPrints,          1,  0},
    {"locate",        	basLocate,          2,  0},
    {"atx",           	basAtx,             0,  0},
    {"aty",           	basAty,             0,  0},
    {"curson",        	basCursOn,          0,  0},
    {"cursoff",       	basCursOff,         0,  0},
    {"inputs",        	basInputs,          2,  0},
    {"zoneinputs",    	basZoneInputs,      4,  0},

//    Sounds and music
    {"isenabledsound",  basIsEnabledSound,  0,  0},
    {"soundenabled",    basIsEnabledSound,  0,  0},

    {"soundexists",     basSoundExists,	    1,  0},
    {"deletesound",     basDeleteSound,	    1,  0},
    {"copysound",       basCopySound,	    2,  0},

    {"musicexists",  	basMusicExists,	    0,  0},

    {"playsound",     	basPlaySound,       2,  1},
    {"playfreqsound",   basPlayFreqSound,   3,  1},
    {"volumesound",   	basVolumeSound,     1,  1},
    {"soundvolume",   	basVolumeSound,     1,  1},
    {"stopsound",     	basStopSound,       0,  1},
    {"pausesound",     	basPauseSound,      0,  1},
    {"resumesound",     basResumeSound,     0,  1},
    {"vumetersound",    basVuMeterSound,    0,  1},
    {"sound3d",		basPositionSound,   3,  0},
    {"positionsound",   basPositionSound,   3,  0},
    {"soundchannels",   basSoundChannels,   1,  0},

    {"playmusic",     	basPlayMusic,       1,  0},
    {"positionmusic",  	basPositionMusic,   1,  0},
    {"stopmusic",     	basStopMusic,       0,  0},
    {"pausemusic",     	basPauseMusic,      0,  0},
    {"resumemusic",    	basResumeMusic,     0,  0},
    {"rewindmusic",    	basRewindMusic,     0,  0},
    {"fademusic",     	basFadeMusic,       0,  1},
    {"volumemusic",   	basVolumeMusic,     0,  1},
    {"musicvolume",   	basVolumeMusic,     0,  1},
    {"speedmusic",   	basSpeedMusic,      1,  0},
    {"musicspeed",   	basSpeedMusic,      1,  0},

//    Keyboard
    {"key",           	basKey,             1,  0},
    {"inkey",         	basInkey,           0,  0},
    {"waitkey",       	basWaitKey,         0,  1},

//    Mouse
    {"xmouse",        	basXMouse,          0,  0},
    {"ymouse",        	basYMouse,          0,  0},
    {"mousex",        	basXMouse,          0,  0},
    {"mousey",        	basYMouse,          0,  0},
    {"xmousescreen",  	basXMouseScreen,    1,  0},
    {"ymousescreen",  	basYMouseScreen,    1,  0},
    {"mousescreenx",  	basXMouseScreen,    1,  0},
    {"mousescreeny",  	basYMouseScreen,    1,  0},
    {"bmouse",        	basBMouse,          0,  0},
    {"mousebutton",    	basBMouse,          0,  0},
    {"changemouse",    	basChangeMouse,     0,  1},
    {"mousepointer",   	basChangeMouse,     0,  1},
    {"locatemouse",    	basLocateMouse,     2,  0},
    {"placemouse",    	basLocateMouse,     2,  0},
    {"mouseshow",     	basMouseShow,       0,  0},
    {"showmouse",     	basMouseShow,       0,  0},
    {"mousehide",     	basMouseHide,       0,  0},
    {"hidemouse",     	basMouseHide,       0,  0},
    {"mousezone",     	basMouseZone,       4,  0},

//    Joystick

    {"numjoysticks",    basNumJoySticks,    0,  0},
    {"namejoystick",    basNameJoyStick,    1,  0},
    {"numaxesjoystick", basNumAxesJoyStick, 1,  0},
    {"numballsjoystick",basNumBallsJoyStick,1,  0},
    {"numhatsjoystick", basNumHatsJoyStick, 1,  0},
    {"numbuttonsjoystick",basNumButtonsJoyStick,1,  0},
    {"getaxisjoystick", basGetAxisJoyStick, 2,  0},
    {"gethatjoystick", basGetHatJoyStick,   2,  0},
    {"getbuttonjoystick", basGetButtonJoyStick, 2,  0},
    {"xgetballjoystick", basXGetBallJoyStick, 2,  0},
    {"ygetballjoystick", basYGetBallJoyStick, 2,  0},
    {"joy",         	basJoy,             1,  0},
    {"bjoy",          	basBJoy,            1,  0},
    {"joybuttons",     	basBJoy,            1,  0},
    {"fire",          	basBJoy,            1,  0},
    {"waitbjoy",      	basWaitBJoy,        1,  1},

//    SDLtime
    {"wait",          	basWait,            1,  0},
    {"timer",         	basTimer,           0,  0},
